### PR TITLE
Pagination styling first draft - Based on 3.5.x

### PR DESCRIPTION
**Pull request by mmexvr**
**Describe pull-request**</br>
_Intial styling for pagination_

- border-radius
- padding
- font-size 
- Color
- Active state

**Solving issue**</br>
Fixes a part of progressbar in: #11 and #31 

**Additional context**<br/>
- Based on 3.5.x

### CODE REVIEW

**Comment by mmexvr** [comment]
Conflict fixed

**Comment by mmexvr** [comment]
Add pagination in storybook when this is merged

**Comment by helloimela** [comment]
Add font-weight bold to the active state

**Comment by mmexvr** [comment]
> Add font-weight bold to the active state

Added bold for active

**Review by helloimela — APPROVED** [review]

**Pull request merged**
