### PR TITLE
Improvement/restructuring of components

### PR DESCRIPTION
**Pull request by awinny**
**Describe pull-request**
- Changed naming of elements and components
- Added color mixins for theme related components
- Added missing component primary colors

### CODE REVIEW

**Comment by awinny** [comment]
Remember to merge #12 before merging this

**Review by helloimela — CHANGES_REQUESTED** [review]
- Add font-weight bold on button
- Change alert background & table background
- Remove text shadow on text and use color value

**Comment by mmexvr** [comment]
Needs fallback in IE for colors variables

**Review by helloimela — APPROVED** [review]
nice!

**Pull request merged**
